// Generated by EclipseP5Exporter: Sun Nov 16 12:53:23 CST 2014




import com.phidgets.InterfaceKitPhidget;
import com.phidgets.PhidgetException;




	void setup() {
	    this.size(100, 100);
	    InterfaceKitPhidget ifkit;
        try
        {
            ifkit = new InterfaceKitPhidget();
            ifkit.openAny();
            ifkit.waitForAttachment();

            int value = ifkit.getSensorValue(0);
            System.out.println(value);
        }
        catch (PhidgetException e)
        {
            e.printStackTrace();
        }
	}

	void draw() {
	}

